apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    srv: api
spec:
  selector:
    srv: api
  type: NodePort
  ports:
   - port: 3000
     nodePort: 30000
---
apiVersion: v1
kind: Pod
metadata:
  # srv: api
  labels:
    srv: api
  name: mypod
spec:
  # ports:
  #   - port: 3000
  #     protocol: TCP
  containers:
    - name: opencv-yolo
      image: kkbankol/opencv_yolo_pod
